
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jun 27 19:48:32 BRT 2007
//----------------------------------------------------

package trabalho3;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ATRIBUICAO = 4;
  public static final int SE = 9;
  public static final int ABRECOLCHETE = 2;
  public static final int LETRA = 12;
  public static final int EOF = 0;
  public static final int NUMERO = 11;
  public static final int DECREMENTAR = 8;
  public static final int FECHACOLCHETE = 3;
  public static final int error = 1;
  public static final int ENQUANTO = 10;
  public static final int IMPRIMIR = 5;
  public static final int INCREMENTAR = 7;
  public static final int LER = 6;
}

